# Generated by Django 2.2.7 on 2021-01-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_auto_20210122_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
